use_frameworks!

target 'utilswift_Example' do
  pod 'utilswift', :path => '../'

  target 'utilswift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
